name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1      
    - name: Test, build and deploy
      run: |
        echo Start test!
        echo Finish test!
        echo -------------
        echo Start build!
        echo Finish build!
        echo -------------
        echo Start deploy!
        echo Finish deploy!
