name: test-before-push-master

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1      
    - name: Test
      run: |
        echo Start test!
        echo Finish test!
